// <auto-generated />
using System;
using AirAnalysis.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirAnalysis.DAL.Migrations
{
    [DbContext(typeof(AirAnalysisDbContext))]
    [Migration("20251128205726_AddMaterializedView")]
    partial class AddMaterializedView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirAnalysis.DAL.Entities.Phenomen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Phenomens");
                });

            modelBuilder.Entity("AirAnalysis.DAL.Entities.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("AirAnalysis.DAL.Entities.RecordData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRecord")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhenomenId")
                        .HasColumnType("int");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PhenomenId");

                    b.HasIndex("PlaceId", "DateRecord", "PhenomenId")
                        .HasDatabaseName("idx_recorddata_main");

                    b.ToTable("RecordData", (string)null);
                });

            modelBuilder.Entity("AirAnalysis.DAL.Entities.RecordDataDailyView", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasColumnName("Date");

                    b.Property<int?>("PhenomenId")
                        .HasColumnType("int")
                        .HasColumnName("PhenomenId");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int")
                        .HasColumnName("PlaceId");

                    b.Property<long>("RecordCount")
                        .HasColumnType("bigint")
                        .HasColumnName("RecordCount");

                    b.Property<double?>("SumValue")
                        .HasColumnType("float")
                        .HasColumnName("SumValue");

                    b.ToTable((string)null);

                    b.ToView("vw_RecordDataDaily", "dbo");
                });

            modelBuilder.Entity("AirAnalysis.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AirAnalysis.DAL.Entities.RecordData", b =>
                {
                    b.HasOne("AirAnalysis.DAL.Entities.Phenomen", "Phenomen")
                        .WithMany("RecordDatas")
                        .HasForeignKey("PhenomenId");

                    b.HasOne("AirAnalysis.DAL.Entities.Place", "Place")
                        .WithMany("RecordDatas")
                        .HasForeignKey("PlaceId");

                    b.Navigation("Phenomen");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("AirAnalysis.DAL.Entities.Phenomen", b =>
                {
                    b.Navigation("RecordDatas");
                });

            modelBuilder.Entity("AirAnalysis.DAL.Entities.Place", b =>
                {
                    b.Navigation("RecordDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
